import { writeFileSync, mkdirSync, existsSync } from 'fs';
import { join } from 'path';
import chalk from 'chalk';

export class SecurityReportGenerator {
  constructor(outputDir = './reports') {
    this.outputDir = outputDir;
    this.ensureOutputDir();
  }

  ensureOutputDir() {
    if (!existsSync(this.outputDir)) {
      mkdirSync(this.outputDir, { recursive: true });
    }
  }

  generate(results, format = 'md') {
    const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
    const filename = `security-report-${timestamp}.${format}`;
    const filepath = join(this.outputDir, filename);

    let content;
    if (format === 'json') {
      content = JSON.stringify(results, null, 2);
    } else {
      content = this.generateMarkdown(results);
    }

    writeFileSync(filepath, content, 'utf-8');
    console.log(chalk.green(`\n✅ Report saved: ${filepath}`));
    return filepath;
  }

  generateMarkdown(results) {
    const lines = [
      '# 🔴 Red CLI - Security Assessment Report',
      '',
      '## Executive Summary',
      '',
      `| Metric | Value |`,
      `|--------|-------|`,
      `| Target | ${results.target || 'N/A'} |`,
      `| Date | ${new Date().toISOString()} |`,
      `| Duration | ${results.duration || 'N/A'} |`,
      '',
      '### Severity Overview',
      ''
    ];

    const severityCounts = { critical: 0, high: 0, medium: 0, low: 0, info: 0 };
    for (const f of results.findings || []) {
      const sev = (f.severity || 'info').toLowerCase();
      if (severityCounts[sev] !== undefined) severityCounts[sev]++;
    }

    lines.push(
      `| Severity | Count |`,
      `|----------|-------|`,
      `| 🔴 Critical | ${severityCounts.critical} |`,
      `| 🟠 High | ${severityCounts.high} |`,
      `| 🟡 Medium | ${severityCounts.medium} |`,
      `| 🟢 Low | ${severityCounts.low} |`,
      `| 🔵 Info | ${severityCounts.info} |`,
      ''
    );

    if (results.findings && results.findings.length > 0) {
      lines.push('## Findings', '');
      for (const finding of results.findings) {
        const icon = this.getSeverityIcon(finding.severity);
        lines.push(
          `### ${icon} ${finding.title || finding.name || 'Untitled'}`,
          '',
          `**Severity:** ${finding.severity || 'unknown'}`,
          `**Type:** ${finding.type || 'N/A'}`,
          ''
        );

        if (finding.message) {
          lines.push(`> ${finding.message}`, '');
        }
        if (finding.file) {
          lines.push(`**File:** \`${finding.file}\``);
        }
        if (finding.line) {
          lines.push(`**Line:** ${finding.line}`, '');
        }
        lines.push('---', '');
      }
    }

    if (results.phases) {
      lines.push('## Assessment Phases', '');
      for (const [phase, data] of Object.entries(results.phases)) {
        lines.push(`### ${this.formatPhaseName(phase)}`, '');
        if (data.findings) {
          lines.push(`- Findings: ${data.findings.length}`, '');
        }
      }
    }

    lines.push(
      '## Recommendations',
      '',
      '1. **Critical/High Findings**: Address immediately - these pose significant risk.',
      '2. **Medium Findings**: Plan remediation within 30 days.',
      '3. **Low Findings**: Include in regular maintenance cycles.',
      '4. **Info Items**: Review for potential future improvements.',
      '',
      '---',
      '*Generated by Red CLI Security Engine*'
    );

    return lines.join('\n');
  }

  getSeverityIcon(severity) {
    const s = (severity || '').toLowerCase();
    return {
      critical: '🔴',
      high: '🟠',
      medium: '🟡',
      low: '🟢',
      info: '🔵',
      pass: '✅'
    }[s] || '⚪';
  }

  formatPhaseName(name) {
    return name
      .replace(/([A-Z])/g, ' $1')
      .replace(/^./, s => s.toUpperCase())
      .trim();
  }

  generateHTML(results) {
    const html = `
<!DOCTYPE html>
<html>
<head>
  <title>Security Report - ${results.target || 'Assessment'}</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; line-height: 1.6; max-width: 900px; margin: 0 auto; padding: 20px; background: #1a1a2e; color: #eee; }
    h1 { color: #ff6b6b; border-bottom: 2px solid #ff6b6b; padding-bottom: 10px; }
    h2 { color: #feca57; margin-top: 30px; }
    h3 { color: #48dbfb; }
    table { border-collapse: collapse; width: 100%; margin: 20px 0; }
    th, td { border: 1px solid #333; padding: 12px; text-align: left; }
    th { background: #2d2d44; }
    .critical { color: #ff6b6b; font-weight: bold; }
    .high { color: #ff9f43; font-weight: bold; }
    .medium { color: #feca57; }
    .low { color: #1dd1a1; }
    .info { color: #54a0ff; }
    .finding { background: #2d2d44; padding: 15px; margin: 10px 0; border-radius: 8px; border-left: 4px solid #ff6b6b; }
    code { background: #0f0f1a; padding: 2px 6px; border-radius: 4px; }
  </style>
</head>
<body>
  <h1>🔴 Security Assessment Report</h1>
  <p><strong>Target:</strong> ${results.target || 'N/A'}</p>
  <p><strong>Date:</strong> ${new Date().toISOString()}</p>

  <h2>Severity Summary</h2>
  <table>
    <tr><th>Severity</th><th>Count</th></tr>
    <tr><td class="critical">Critical</td><td>${results.findings?.filter(f => f.severity === 'critical').length || 0}</td></tr>
    <tr><td class="high">High</td><td>${results.findings?.filter(f => f.severity === 'high').length || 0}</td></tr>
    <tr><td class="medium">Medium</td><td>${results.findings?.filter(f => f.severity === 'medium').length || 0}</td></tr>
    <tr><td class="low">Low</td><td>${results.findings?.filter(f => f.severity === 'low').length || 0}</td></tr>
  </table>

  <h2>Findings</h2>
  ${(results.findings || []).map(f => `
    <div class="finding">
      <h3>${f.title || 'Untitled'}</h3>
      <p><strong>Severity:</strong> <span class="${f.severity}">${f.severity || 'unknown'}</span></p>
      <p>${f.message || ''}</p>
      ${f.file ? `<p><code>${f.file}</code>${f.line ? `:${f.line}` : ''}</p>` : ''}
    </div>
  `).join('')}

  <hr>
  <p style="color: #666;">Generated by Red CLI Security Engine</p>
</body>
</html>`;

    const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
    const filepath = join(this.outputDir, `security-report-${timestamp}.html`);
    writeFileSync(filepath, html, 'utf-8');
    console.log(chalk.green(`\n✅ HTML Report saved: ${filepath}`));
    return filepath;
  }

  quickSummary(results) {
    const severityCounts = { critical: 0, high: 0, medium: 0, low: 0 };
    for (const f of results.findings || []) {
      const sev = (f.severity || '').toLowerCase();
      if (severityCounts[sev] !== undefined) severityCounts[sev]++;
    }

    console.log(chalk.red(`
╭─ 📊 Security Report Summary ─────────────────────────────────╮
│  Target: ${results.target || 'N/A'}
│  Findings: ${results.findings?.length || 0}
│
│    🔴 Critical: ${severityCounts.critical}
│    🟠 High: ${severityCounts.high}
│    🟡 Medium: ${severityCounts.medium}
│    🟢 Low: ${severityCounts.low}
╰──────────────────────────────────────────────────────────────╯
    `));
  }
}

export default SecurityReportGenerator;